### ISSUE TITLE
ansible-role specified does not exist as a git repo

### ISSUE THREAD

**Issue by bbaassssiiee** [Duffney/becomeansible#12]
https://github.com/Duffney/becomeansible/blob/54de10742a97937099a1feaf1555d02b0501fdda/chapter-08/roles/requirements.yml#L1

Did you forget to decouple it?

**Comment by duffney** [comment]
I had forgotten to update the git URL... Thanks for pointing that out.

The full story is I originally plan on doing some choco for business roles. But I accidentally created a public repo with the license which was bad. In my haste, I didn't clean everything up.

I appreciate you taking the time to open the issue. 

It's now fixed with https://github.com/Duffney/becomeansible/commit/ab246cc7e4e8c914b717003888e2dea04d26ae6b
